CREATE TABLE NYC.Staging(
    StgNYC_sk                   int               NOT NULL,
    ResturantID                 bigint            NULL,
    ResturantName               nvarchar(254)     NULL,
    ResturantLocation           nvarchar(254)     NULL,
    BuildingNumber              nvarchar(254)     NULL,
    Street                      nvarchar(254)     NULL,
    ZipCode                     nvarchar(10)      NULL,
    Phone                       nvarchar(15)      NULL,
    CuisineDesc                 nvarchar(254)     NULL,
    Inspectiondate              nvarchar(20)      NULL,
    InspectionAction            nvarchar(254)     NULL,
    ViolationCode               nvarchar(254)     NULL,
    ViolationDesc               nvarchar(1000)    NULL,
    CriticalFlag                nvarchar(254)     NULL,
    InspectionScore             bigint            NULL,
    InspectionGrade             nvarchar(5)       NULL,
    GradeDate                   nvarchar(20)      NULL,
    RecordDate                  nvarchar(20)      NULL,
    InspectionType              nvarchar(254)     NULL,
    Latitude                    float             NULL,
    Longitude                   float             NULL,
    CommunityBoard              bigint            NULL,
    CouncilDistrict             nvarchar(254)     NULL,
    CensusTract                 nvarchar(254)     NULL,
    BIN                         bigint            NULL,
    BBL                         bigint            NULL,
    NTA                         nvarchar(10)      NULL,
    LocationPoint               nvarchar(254)     NULL,
    [INSPECTION DATE_modified]  date              NULL,
    [GRADE DATE_modified]       date              NULL,
    [RECORD DATE_modified]      date              NULL,
    DI_CreateDate               datetime          NULL,
    DI_WorkflowFileName         nvarchar(254)     NULL,
    CONSTRAINT PK1 PRIMARY KEY CLUSTERED (StgNYC_sk)
)

go